#!/bin/sh
set -u

ADDR="riga"

if [ $# -eq 0 ]; then
    ssh root@"${ADDR}" "ls /home/git/" | xargs -L1 basename -s .git
    exit 0
fi

while [ $# -gt 0 ]; do
    case "$1" in
    prepare)
        ssh root@"$ADDR" "
        if ! id -u git >/dev/null 2>&1; then
            useradd -m -s /usr/bin/git-shell git
        fi
        "
        shift
        ;;
    -a | --address)
        [ $# -lt 2 ] && {
            echo "$1 requires an argument"
            exit 1
        }
        ADDR="$2"
        shift 2
        ;;
    key)
        [ $# -lt 2 ] && {
            echo "$1 requires an argument"
            exit 1
        }
        key="$2"
        echo "$key" | ssh root@"${ADDR}" "
            mkdir -p /home/git/.ssh && chmod 700 /home/git/.ssh
            keys=/home/git/.ssh/authorized_keys
            touch \"\$keys\" && chmod 600 \"\$keys\"
            read -r new_key
            if ! grep -qF \"\$new_key\" \"\$keys\"; then
                printf '%s\n' \"\$new_key\" >> \"\$keys\"
            fi
            chown -R git:git /home/git/.ssh
            "
        shift 2
        ;;
    init | rm)
        action="$1"
        [ $# -lt 2 ] && {
            echo "$action requires a repo name"
            exit 1
        }
        repo="$2"
        [ "${repo%.git}" = "$repo" ] && repo="$repo.git"

        if [ "$action" = "init" ]; then
            ssh root@"${ADDR}" "
            mkdir -p /home/git/'$repo' &&\
            git init --bare /home/git/'$repo' &&\
            chown -R git:git /home/git/'$repo'\
            "
        else
            ssh root@"${ADDR}" "rm -rf /home/git/'$repo'"
        fi
        shift 2
        ;;
    *)
        echo "unknown command: $1"
        exit 1
        ;;
    esac
done
