### General ###
set -g prefix None
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

### Layout stuff ###
bind -n M-q kill-pane
bind -n M-n new-window -c "#{pane_current_path}"
bind -n M-b break-pane
bind -n M-m select-pane -m
bind -n M-s swap-pane \; select-pane -M
bind -n M-i split-pane -h -c "#{pane_current_path}"
bind -n M-o split-pane -v -c "#{pane_current_path}"
bind -n M-I join-pane -h \; select-pane -M
bind -n M-O join-pane -v \; select-pane -M
bind -n M-Q kill-session

### Visual mode ###
bind -n M-v if-shell -F "#{pane_in_mode}" "send-keys -X cancel" "copy-mode"
bind-key -T copy-mode-vi v if-shell -F "#{selection_present}" "send -X clear-selection" "send -X begin-selection"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind -n M-p run "wl-paste -n | tmux load-buffer - && tmux paste-buffer -p"
bind -n M-з run "wl-paste -n | tmux load-buffer - && tmux paste-buffer -p"

### Mouse ###
bind-key -n MouseDown3Pane display-menu -T "#[align=centre] #W " -x M -y M \
    "paste"  p "run-shell 'wl-paste -n | tmux load-buffer - ; tmux paste-buffer'" \
    "new-window" n "new-window -c \"#{pane_current_path}\"" \
    "split-h" h "split-pane -h" \
    "split-v" v "split-pane -v" \
    "kill-pane"   x "kill-pane"

### Movement ###
bind -n M-h if-shell "[ #{pane_at_left} -ne 1 ]" "select-pane -L"
bind -n M-j if-shell "[ #{pane_at_bottom} -ne 1 ]" "select-pane -D"
bind -n M-k if-shell "[ #{pane_at_top} -ne 1 ]" "select-pane -U"
bind -n M-l if-shell "[ #{pane_at_right} -ne 1 ]" "select-pane -R"
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 2
bind -n M-K resize-pane -U 2
bind -n M-L resize-pane -R 5
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-! swap-window -t 1 \; select-window -t 1
bind-key -n M-@ swap-window -t 2 \; select-window -t 2
bind-key -n M-# swap-window -t 3 \; select-window -t 3
bind-key -n M-$ swap-window -t 4 \; select-window -t 4
bind-key -n M-% swap-window -t 5 \; select-window -t 5
bind-key -n M-^ swap-window -t 6 \; select-window -t 6
bind-key -n M-& swap-window -t 7 \; select-window -t 7
bind-key -n M-* swap-window -t 8 \; select-window -t 8
bind-key -n M-( swap-window -t 9 \; select-window -t 9
