#!/bin/env bash

hyprpaper &
while ! hyprctl hyprpaper active >/dev/null 2>&1; do
    sleep 0.1
done

DIR="$HOME/pictures/wallpapers"
FILE=$(find "$DIR" -type f \( -iname "*.jpg" -o -iname "*.png" \) | shuf -n 1)
hyprctl hyprpaper reload ",$FILE"
