general {
    gaps_in = 0
    gaps_out = 0
    col.active_border = rgba(d1d1d1aa)
    col.inactive_border = rgba(1a1a19aa)
}

decoration {
    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

animations {
    enabled = false
}

xwayland {
  force_zero_scaling = true
}

env = GDK_SCALE,2
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,12
env = WALLPAPER,$HOME/pictures/wallpapers/dan-otis-OYFHT4X5isg-unsplash.jpg
