general {
    gaps_in = 0
    gaps_out = 0
    col.active_border = rgba(d1d1d1aa)
    col.inactive_border = rgba(1a1a19aa)
}

decoration {
    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

animations {
    enabled = false
}

