monitor=eDP-1,3200x2000@60Hz,0x0,2

input {
    kb_layout = us, ru
    kb_options = grp:caps_toggle
    repeat_rate = 25
    repeat_delay = 250

    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

