windowrule = tile on, match:xwayland 1
windowrule = suppress_event maximize, match:class .*
windowrule = no_initial_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1

workspace = w[tv1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
