$terminal = alacritty
$browser = firefox
$fileManager = nemo
$menu = fuzzel

exec-once = $XDG_CONFIG_HOME/hypr/scripts/wallpaper & hypridle & waybar & swaync & nm-applet & blueman-applet
exec-once = systemctl --user import-environment HYPRLAND_INSTANCE_SIGNATURE

source = $XDG_CONFIG_HOME/hypr/conf.d/*.conf
