$terminal = alacritty
$browser = firefox
$fileManager = nemo
$menu = fuzzel

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec-once = hyprpaper & hypridle & waybar & swaync
exec-once = systemctl --user import-environment HYPRLAND_INSTANCE_SIGNATURE

source = $XDG_CONFIG_HOME/hypr/conf.d/*.conf
