$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun

source = $XDG_CONFIG_HOME/hypr/conf.d/*.conf

exec-once = hyprpaper & waybar & swaync

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
